apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app.kubernetes.io/name: {{ include "backend.name" . }}
    helm.sh/chart: {{ include "backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "grpc"
    # ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
    - secretName: backend-certs
      hosts:
        - {{ .Values.ingress.server.prod.host }}
        - {{ .Values.ingress.server.staging.host }}
  rules:
    - host: {{ .Values.ingress.server.prod.host }}
      http:
        paths:
          - path: {{ .Values.ingress.server.prod.path }}
            backend:
              serviceName: {{ .Release.Name }}-server-blue
              servicePort: 50051
    - host: {{ .Values.ingress.server.staging.host }}
      http:
        paths:
          - path: {{ .Values.ingress.server.staging.path }}
            backend:
              serviceName: {{ .Release.Name }}-server-green
              servicePort: 50051
