---
kind: secret

external_data:
  docker_username:
    path: secret/ci
    name: docker_username
  docker_password:
    path: secret/ci
    name: docker_password
  k8s_apiserver_addr:
    path: secret/ci
    name: k8s_apiserver_addr
  k8s_ca:
    path: secret/ci
    name: k8s_ca
  k8s_token:
    path: secret/ci
    name: k8s_token
---
kind: pipeline
name: test

steps:
  - name: tests
    image: golang:alpine
    commands: ["CGO_ENABLED=0 go test ./... -mod=vendor"]

trigger:
  event:
    - push
  branch:
    - staging

---
kind: pipeline
name: staging

steps:
  - name: build-client
    image: plugins/docker
    settings:
      repo: risla8/backend-client
      tags: ${DRONE_COMMIT_SHA:0:8}
      dockerfile: ./ci/docker/Dockerfile.client
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: build-server
    image: plugins/docker
    settings:
      repo: risla8/backend-server
      tags: ${DRONE_COMMIT_SHA:0:8}
      dockerfile: ./ci/docker/Dockerfile.server
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: deploy
    image: dtzar/helm-kubectl:2.11.0
    commands: ["apk add grep", "cd ./ci/scripts && ./deploy.sh"]
    environment:
      APISERVER_ADDR:
        from_secret: k8s_apiserver_addr
      HELM_INSTALL: backend
      CA:
        from_secret: k8s_ca
      TOKEN:
        from_secret: k8s_token
      STAGING: true
      TAG: ${DRONE_COMMIT_SHA:0:8}
    depends_on: [build-client, build-server]

depends_on:
  - test

trigger:
  event:
    - push
  branch:
    - staging
  status:
    - success
        
---
kind: pipeline
name: pr

steps:
  - name: test
    image: golang:alpine
    commands: ["CGO_ENABLED=0 go test ./... -mod=vendor"]

trigger:
  event:
    - pull_request

---
kind: pipeline
name: master

steps:
  - name: switch-environments
    image: dtzar/helm-kubectl:2.11.0
    commands: ["apk add grep", "cd ./ci/scripts && ./deploy.sh"]
    environment:
      APISERVER_ADDR:
        from_secret: k8s_apiserver_addr
      CA:
        from_secret: k8s_ca
      TOKEN:
        from_secret: k8s_token
      HELM_INSTALL: backend
      TAG: ${DRONE_COMMIT_SHA:0:8}
      SWITCH: true

trigger:
  event:
    - push
  branch:
    - master
